---
title: "Tidying Data"
author: "Desik Somasundaram"
date: "8/16/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
```

```{r}
wb_indicators <- read_csv(here("data", "wb_indicators.csv"), na = c("..", ""))
```
## Reshape so that year is a single column

```{r}
wb_indicators_long <- wb_indicators %>%  
  pivot_longer(cols = '2001 [YR2001]' : '2020 [YR2020]',
               names_to = "year", 
               values_to = "indicator_value")


```

# Clean up year column

```{r}
wb_data_sep <- wb_indicators_long %>% 
  separate(col = year, into = c("year", "year_chr"), sep = " ") %>% 
  select(-year_chr, -'Country Code', -'Series Code')

```


```{r}
df <- tribble(~name, ~A,~B, ~C, 
              "teddy", 4 , 5, 6, 
              "khora", 9, 10 , 11)
df<- pivot_longer(df, cols = "A":"C", names_to = "dog food type", values_to = "pounds")
df_wide <-pivot_wider(df, names_from = "dog food type", values_from = "pounds")
```

## Pivot Wider to get all indicators into their own column

```{r}
wb_data_tidy <- wb_data_sep %>% 
  drop_na('Series Name') %>% 
  pivot_wider(names_from = 'Series Name', values_from = indicator_value)

names(wb_data_tidy) <-c("country", "year", "access_clean_fuels", "access_electricity", "co2_emissions", "fossil_fuel_cons", "water_stress")

wb_data_tidy <- wb_data_tidy %>%
  rename(country_name = country)
```

```{r}


```

